### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by mitchellreiss** [Mikhail-Kashin/Instagram-Clone-Group-project-week-20#2]
### Posts
- [ ] Add image_url column
- [ ] Remove like_id column
### Likes
- [ ] Add post_id column
### Follows
- [ ] Follows needs a follower_id column (This will hold reference to a Users table PK)
### Comments
- [ ] Remove like_id (If you want to be able to do a like on a comment you must use another join table to join Users and Comments)
- [ ] Change "string" column name to "body"

## User Stories
- [ ] Separate out Likes and Comments into two different sections
- [ ] Likes on Comments and Likes on Posts are two different features. I suggest removing liking comments as a key feature and only doing likes on Posts. Liking comments can be a bonus feature but should have a separate user story section if you decide to go that route.

**Comment by ibuckhold** [comment]
Just finished fixing those issues. Thank you!
